todos/urls.py
from django.urls import path
from . import views

app_name='todos'

urlpatterns = [
    path('', views.index,name='index'),
    path('create/', views.create, name='create'),
    path('update/<int:pk>', views.update, name='update'),
    path('delete/<int:pk>', views.delete, name='delete'),
]

wunderlist/urls.py
from django.contrib import admin
from django.urls import path, include
from todos import views
from decouple import config

token = config('TOKEN')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todos/', include('todos.urls')),
    path(f'{token}/', views.telegram),
]

todos/models.py
from django.db import models

# Create your models here.

class Todo(models.Model):
    title = models.CharField(max_length=100)
    due_date = models.DateField()

todos/views.py
from django.shortcuts import render, redirect, get_object_or_404, HttpResponse
from .models import Todo
from django.views.decorators.csrf import csrf_exempt
import json
from decouple import config
import requests

def sendMessage(request, title, due_date):
    base_url = 'https://api.telegram.org'
    token = config('TOKEN')
    send_to_sir = f'{title} (D-day: {due_date})'
    method = 'sendMessage'
    chat_ids = ['873780022', '861812746']
    for chat_id in chat_ids:
        url = f'{base_url}/bot{token}/{method}?chat_id={chat_id}&text={send_to_sir}'
        requests.get(url)


def index(request):
    todos=Todo.objects.all()
    context={
        'todos':todos
    }
    return render(request, 'todos/index.html', context)


def create(request):
    if request.method =='POST':
        title = request.POST.get('title')
        due_date = request.POST.get('due-date')
        Todo.objects.create(title=title, due_date=due_date)
        sendMessage(request, title, due_date)
        return redirect('todos:index')
    else:
        return render(request, 'todos/create.html')


def update(request,pk):
    todo=get_object_or_404(Todo, id=pk)
    if request.method=='POST':
        title= request.POST.get('title')
        due_date= request.POST.get('due-date')
        todo.title=title
        todo.due_date=due_date
        todo.save()
        return redirect('todos:index')
    else:
        context={
            'todo':todo,
        }
        return render(request, 'todos/update.html',context)

def delete(request,pk):
    todo=get_object_or_404(Todo, id=pk)
    todo.delete()
    return redirect('todos:index')


@csrf_exempt
def telegram(request):
    res = json.loads(request.body)
    text = res.get('message').get('text')
    chat_id = res.get('message').get('chat').get('id')
    base = 'https://api.telegram.org'
    token = config('TOKEN')
    url = f'{base}/bot{token}/sendMessage?text={text}&chat_id={chat_id}'
    requests.get(url)
    return HttpResponse('가랏')

todos/templates/todos/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>WunderList</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item p-2">
            <a href="{% url 'todos:create' %}">글 작성하기</a>
          </li>
          <li class="nav-item p-2">
            <a href="{% url 'todos:index' %}">글 모아보기</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">  
      {% block body %}
      {% endblock %}
    </div>  
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

todos/templates/todos/create.html
{% extends 'todos/base.html' %}

{% block body %}
<h1>할일 추가</h1>
<form action="{% url 'todos:create' %}" method="post">
  {% csrf_token %}
  <label for="title">할일 : </label>
  <input type="text" name="title" class="form-control">

  <label for="due-date">기한 : </label>
  <input type="date" name="due-date" class="form-control">
  <input type="submit">
</form>
{% endblock %}

todos/templates/todos/index.html
{% extends 'todos/base.html' %}

{% block body %}
<h1>게시판</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope='col'>id</th>
      <th scope='col'>할일</th>
      <th scope='col'>기한</th>
    </tr>
  </thead>
  <tbody>
    {% for todo in todos %}
    <tr>
      <th scope='row'>{{todo.id}}</th>
      <td>{{todo.title}}</td>
      <td>{{todo.due_date}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

todos/templates/todos/update.html
{% extends 'todos/base.html' %}

{% block body %}
<h1>여기는 새글 작성입니다.</h1>
<form action="{% url 'todos:update' todo.id %}" method="post">
  {% csrf_token %}
  <input type="text" name="title" value="{{todo.title}}">
  <input type="date" name="due-date" value="{{todo.due_date|date:'Y-m-d'}}">
  <input type="submit">
</form>
{% endblock %}